title: Mergical Notes
theme: minima

markdown: kramdown

header_pages:
  - graphics/index.md
  - unreal/index.md
  - cpp/index.md
  - systems/index.md
  - algorithms/index.md

titles_from_headings:
  strip_title: true